protected/models/Message.php
<?php

/**
 * This is the model class for table "message".
 *
 * The followings are the available columns in table 'message':
 * @property string $id
 * @property string $from_user_id
 * @property string $to_user_id
 * @property string $body
 * @property integer $created_at
 */
class Message extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'message';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('from_user_id, to_user_id, created_at', 'length', 'max'=>11),
			array('body', 'length', 'max'=>1000),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, from_user_id, to_user_id, body, created_at', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'author' => array(self::BELONGS_TO, 'User', 'from_user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'from_user_id' => 'From User',
			'to_user_id' => 'To User',
			'body' => 'Body',
			'created_at' => 'Created At',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('from_user_id',$this->from_user_id,true);
		$criteria->compare('to_user_id',$this->to_user_id,true);
		$criteria->compare('body',$this->body,true);
		$criteria->compare('created_at',$this->created_at,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Message the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

    public function toUser($userId)
    {
        $this->getDbCriteria()->mergeWith(array(
            'order'=>'created_at DESC',
            'condition' => 'to_user_id = :to_user_id',
            'params' => array(':to_user_id'=> (int)$userId),
        ));
        return $this;
    }

    public function beforeSave()
    {
        if(parent::beforeSave()){
            $this->from_user_id = (int)Yii::app()->user->id;
            $this->created_at = time();
            return true;
        }
        return false;
    }
}

protected/models/MessageForm.php
<?php

class MessageForm extends CFormModel
{
    public $to_user_id;
    public $message;

    /**
     * Declares the validation rules.
     * The rules state that username and password are required,
     * and password needs to be authenticated.
     */
    public function rules()
    {
        return array(
            // username and password are required
            array('to_user_id, message', 'required'),
            // rememberMe needs to be a boolean
            array('to_user_id', 'integer'),
        );
    }

    /**
     * Declares attribute labels.
     */
    public function attributeLabels()
    {
        return array(
            'message'=>'Message',
        );
    }
}

protected/controllers/MessageController.php
<?php

/**
 * Class MessageController
 */
class MessageController extends BaseController
{
    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'users'=>array('*'),
                'actions'=>array('list'),
            ),
            array('allow',
                'users'=>array('@'),
                'actions'=>array('send', 'delete'),
            ),
            array('deny',
                'users'=>array('*'),
            ),
        );
    }

    public function actionList()
    {
        $toUserId = (int)$_GET['id'];
        $model = new Message();
        $formId = 'message-form';

        $this->setPageTitle('Сообщения');

        $list = Message::model()->toUser($toUserId)->findAll();

        $this->render('list', array(
            'toUserId' => $toUserId,
            'model' => $model,
            'formId' => $formId,
            'list' => $list
        ));
    }

    public function actionSend()
    {
        if(Yii::app()->request->isAjaxRequest)
        {
            $model = new Message();
            $model->attributes = $_POST['Message'];
            if($model->validate() && $model->save()){
                echo $this->renderPartial('_item', array('item' => $model));
                Yii::app()->end();
            }
        }
        throw new CHttpException(400,'Неправильный запрос');
    }

    public function actionDelete()
    {
        if(Yii::app()->request->isAjaxRequest)
        {
            $id = (int)$_POST['id'];
            $model = Message::model()->findByPk($id);
            if(isset($model)){
                $model->delete();
                Yii::app()->end();
            }
        }
        throw new CHttpException(400,'Неправильный запрос');
    }
}

protected/views/message/_item.php
<div class="list-group-item">
    <h4 class="list-group-item-heading">
        От: <?= $item->author->name ?> (<?= $item->author->email ?>) | <?= CTimestamp::formatDate('d.m.Y H:i:s', $item->created_at) ?>
    </h4>
    <p class="list-group-item-text"><?= $item->body ?></p>
</div>

protected/views/message/list.php
<div class="panel panel-default">
    <div class="panel-body">
        <div class="list-group" id="message-list">
            <? foreach($list as $item): ?>
            <div class="list-group-item" id="message-row-<?= $item->id ?>">
                <h4 class="list-group-item-heading">
                    От: <?= $item->author->name ?> (<?= $item->author->email ?>) | <?= CTimestamp::formatDate('d.m.Y H:i:s', $item->created_at) ?>
                </h4>
                <p><?= $item->body ?></p>
                <p>
                <? if(!Yii::app()->user->isGuest && Yii::app()->user->id == $toUserId): ?>
                <?=CHtml::ajaxButton('Удалить',
                        CHtml::normalizeUrl(array('/message/delete')),
                        array(
                            'type' => 'POST',
                            'data' => 'id=' . $item->id,
                            'success' => 'function(response, status, request){
                                $("#message-row-'.$item->id.'").remove();
                            }',
                            'error' => 'function(data) { alert("Error: "+data); }',
                        ),
                        array(
                            'class' => 'btn btn-danger',
                            'confirm' => 'Вы действительно хотите удалить запись?',
                        )
                    )?>
                <? endif; ?>
                </p>
            </div>
            <? endforeach; ?>
        </div>
    </div>
</div>
<? if(!Yii::app()->user->isGuest && Yii::app()->user->id != $toUserId): ?>
<div class="panel panel-default">
    <div class="panel-heading">Написать сообщение</div>
    <div class="panel-body">
        <?
        $form = $this->beginWidget('CActiveForm', array(
            'id' => $formId,
            'enableClientValidation' => true,
            'clientOptions' => array(
                'validateOnSubmit' => true,
            ),
            'htmlOptions' => array(
                'role' => 'form'
            )
        ));
        ?>

        <div>
            <?
            if($model->hasErrors()){
                echo CHtml::errorSummary($model);
            }
            ?>
        </div>

        <?=$form->hiddenField($model, 'to_user_id', array('value' => $toUserId)); ?>
        <div class="form-group">
            <?=$form->textArea($model, 'body', array(
                'class' => 'form-control',
                'required' => true,
                'autofocus' => true,
            ));
            ?>
        </div>
        <div class="form-group">
            <?=CHtml::ajaxSubmitButton('Отправить',
                CHtml::normalizeUrl(array('/message/send')),
                array(
                    'type' => 'POST',
                    'data' => 'js:$("#message-form").serialize()',
                    'success' => 'function(response, status, request){
                        $("#message-list").prepend(response);
                    }',
                    'error' => 'function(data) { alert("Error: "+data); }',
                ),
                array(
                    'type' => 'submit',
                    'class' => 'btn btn-primary',
                )
            );
            ?>
        </div>
        <? $this->endWidget(); ?>
    </div>
</div>
<? endif; ?>